import { breakdowns as mockBreakdowns, machines as mockMachines, pmPlans as mockPmPlans, pmRecords as mockPmRecords, replacements as mockReplacements, spareParts as mockSpareParts } from '@/lib/mock-data';
import { createClient } from '@/lib/supabase/server';
import type { BreakdownRecord, KPI, Machine, PMPlan, PMRecord, ReplacementRecord, SparePart } from '@/types/database';

type Data = { machines:Machine[]; spareParts:SparePart[]; breakdowns:BreakdownRecord[]; replacements:ReplacementRecord[]; pmPlans:PMPlan[]; pmRecords:PMRecord[]; source:'supabase'|'demo' };
const configured = () => Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL && process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);
async function table<T>(name:string): Promise<T[]> { const supabase = await createClient(); const { data, error } = await supabase.from(name).select('*'); if (error) throw error; return (data ?? []) as T[]; }
export async function getData(): Promise<Data> { if (!configured()) return demo(); try { const [machines, spareParts, breakdowns, replacements, pmPlans, pmRecords] = await Promise.all([table<Machine>('machines'), table<SparePart>('spare_parts'), table<BreakdownRecord>('breakdown_records'), table<ReplacementRecord>('spare_part_replacement_records'), table<PMPlan>('preventive_maintenance_plans'), table<PMRecord>('preventive_maintenance_records')]); return { machines, spareParts, breakdowns, replacements, pmPlans, pmRecords, source:'supabase' }; } catch { return demo(); } }
function demo(): Data { return { machines:mockMachines, spareParts:mockSpareParts, breakdowns:mockBreakdowns, replacements:mockReplacements, pmPlans:mockPmPlans, pmRecords:mockPmRecords, source:'demo' }; }
export function addMonths(date:string, months:number) { const d = new Date(`${date}T00:00:00`); d.setMonth(d.getMonth()+months); return d.toISOString().slice(0,10); }
export function daysUntil(date?:string|null) { if (!date) return 9999; const today = new Date(); today.setHours(0,0,0,0); const d = new Date(`${date}T00:00:00`); return Math.round((d.getTime()-today.getTime())/86400000); }
export function scheduleStatus(date?:string|null) { const d=daysUntil(date); if (d<0) return 'OVERDUE'; if (d<=30) return 'DUE_SOON'; return 'OK'; }
export function calculateKpis(data:Data): KPI { const total=data.machines.length || 1; const down=data.machines.filter(m=>['Down','Maintenance'].includes(m.status)).length; const totalDowntime=data.breakdowns.reduce((s,b)=>s+(b.downtime_minutes??0),0); const resolved=data.breakdowns.filter(b=>b.status==='Resolved' || b.resolved_at); const operatingHours=Math.max(total*30*24-totalDowntime/60,1); const pmDue=data.pmPlans.filter(p=>p.is_active && daysUntil(p.next_due_date)<0).length; const pmCompleted=data.pmRecords.length; const pmExpected=Math.max(data.pmPlans.filter(p=>p.is_active).length, pmCompleted); return { availability:Math.round(((total-down)/total)*1000)/10, mtbfHours:Math.round((operatingHours/Math.max(data.breakdowns.length,1))*10)/10, mttrHours:Math.round((totalDowntime/60/Math.max(resolved.length,1))*10)/10, breakdownRate:Math.round((data.breakdowns.length/total)*10)/10, pmCompletionRate:Math.round((pmCompleted/pmExpected)*1000)/10, overduePmCount:pmDue, sparePartsDueCount:data.replacements.filter(r=>daysUntil(r.next_due_date)<=30).length, machineStatusSummary:data.machines.reduce<Record<string,number>>((acc,m)=>{ acc[m.status]=(acc[m.status]??0)+1; return acc;}, {}) }; }
