import { DataTable } from '@/components/DataTable';
import { PageHeader } from '@/components/PageHeader';
import { RecordForm } from '@/components/RecordForm';
import { scheduleStatus, getData } from '@/lib/data';
import { StatusBadge } from '@/components/StatusBadge';

export default async function Page() {
  const data = await getData();
  return <div className="space-y-6"><PageHeader title="Spare Part Replacement Records" description="Preserves prototype logic: selecting a part on any maintenance log updates the machine + part schedule and recalculates next due date from part lifetime." /><div className="flex flex-wrap gap-2"><input className="input max-w-md" placeholder="Search machine or part..." /><button className="btn-primary">Log Replacement</button></div><DataTable rows={data.replacements} columns={[{ key: 'machine', header: 'Machine', render: (record) => data.machines.find((machine) => machine.machine_id === record.machine_id)?.machine_id ?? '—' }, { key: 'part', header: 'Part', render: (record) => data.spareParts.find((part) => part.id === record.spare_part_id)?.name ?? '—' }, { key: 'last', header: 'Last Changed', render: (record) => record.replacement_date }, { key: 'next', header: 'Next Due', render: (record) => record.next_due_date ?? '—' }, { key: 'status', header: 'Status', render: (record) => <StatusBadge value={scheduleStatus(record.next_due_date)} /> }, { key: 'operator', header: 'Operator', render: (record) => record.operator_name }]} /><RecordForm title="Log Spare Part Replacement"><label className="text-sm font-medium">Machine<select className="input mt-1">{data.machines.map((machine) => <option key={machine.machine_id}>{machine.machine_id}</option>)}</select></label><label className="text-sm font-medium">Part<select className="input mt-1">{data.spareParts.map((part) => <option key={part.id}>{part.part_code} — {part.name}</option>)}</select></label><label className="text-sm font-medium">Replacement Date<input className="input mt-1" type="date" /></label><label className="text-sm font-medium">Operator<input className="input mt-1" /></label><label className="text-sm font-medium md:col-span-2">Notes<textarea className="input mt-1" rows={3} /></label></RecordForm></div>;
}
