import { DataTable } from '@/components/DataTable';
import { PageHeader } from '@/components/PageHeader';
import { RecordForm } from '@/components/RecordForm';
import { getData } from '@/lib/data';

export default async function Page() {
  const data = await getData();
  return <div className="space-y-6"><PageHeader title="Preventive Maintenance Records" description="Completed PM work history, replacing PM rows in the prototype Maintenance_Log while keeping operator/date/details tracking." /><div className="flex gap-2"><input className="input max-w-md" placeholder="Search PM records..." /><button className="btn-primary">Log PM</button></div><DataTable rows={data.pmRecords} columns={[{ key: 'machine', header: 'Machine', render: (record) => data.machines.find((machine) => machine.machine_id === record.machine_id)?.machine_id ?? '—' }, { key: 'plan', header: 'Plan', render: (record) => data.pmPlans.find((plan) => plan.id === record.plan_id)?.name ?? 'Ad-hoc PM' }, { key: 'date', header: 'Performed Date', render: (record) => record.performed_date }, { key: 'by', header: 'Completed By', render: (record) => record.completed_by }, { key: 'result', header: 'Result', render: (record) => record.result }, { key: 'notes', header: 'Notes', render: (record) => record.notes ?? '—' }]} /><RecordForm title="Log Preventive Maintenance"><label className="text-sm font-medium">Machine<select className="input mt-1">{data.machines.map((machine) => <option key={machine.machine_id}>{machine.machine_id}</option>)}</select></label><label className="text-sm font-medium">Plan<select className="input mt-1">{data.pmPlans.map((plan) => <option key={plan.id}>{plan.name}</option>)}</select></label><label className="text-sm font-medium">Performed Date<input className="input mt-1" type="date" /></label><label className="text-sm font-medium">Completed By<input className="input mt-1" /></label><label className="text-sm font-medium md:col-span-2">Result / Notes<textarea className="input mt-1" rows={3} /></label></RecordForm></div>;
}
